version: "3"

services:
  # -------------------------------------------------------------------------- #
  # backend service with nestjs                                                #
  # -------------------------------------------------------------------------- #
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - transcendence_net
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  # -------------------------------------------------------------------------- #
  # postgresql database                                                        #
  # -------------------------------------------------------------------------- #
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - transcendence_net

  # -------------------------------------------------------------------------- #
  # redis database                                                             #
  # -------------------------------------------------------------------------- #
  redis:
    image: redis:7.0.8-alpine3.17
    restart: always
    container_name: redis
    ports:
      - 6789:6789
    networks:
      - transcendence_net
    volumes:
      - redis:/data

# ---------------------------------------------------------------------------- #
# networks                                                                     #
# ---------------------------------------------------------------------------- #
networks:
  transcendence_net:

# ---------------------------------------------------------------------------- #
# volumes                                                                      #
# ---------------------------------------------------------------------------- #
volumes:
  database:
  redis:
